apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: "prometheus-metrics-bucket1"
      endpoint: "s3.ap-south-1.amazonaws.com"
      region: "ap-south-1"
      access_key: "AKIASVLTZV72Y6UZXYPT"
      secret_key: "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"
      insecure: false
      signature_version2: false
